# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa0a322d6a00a05f9e6c85c93ef9b61ae832da375e1fcd498b385422469ebd9413477f0323b1f4b9c10366a8afec59f7209e2bbc10c27850c79ae9017bc0524b

test:
  secret_key_base: 568aec5d29c77d06568adb3f63f9ec7105b3b0a1cafb5fb59a089d2d05da2eb6cc5636ef7edafb9c22a463269056c15ce7a42349306016f0bc0c96626d1db30b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
